# tests/test_task_generator.py
"""
Unit tests for scripts/task_generator.py
"""

import pytest
from scripts.task_generator import generate_tasks_for_entry


def _us_nonfinal_entry(**overrides):
    base = {
        "task_status": "Open",
        "country": "US",
        "task_type": "Respond to Non-Final Office Action - 3 Month Deadline",
        "sep_status": None,
        "tier": None,
    }
    base.update(overrides)
    return base


def _us_final_entry(**overrides):
    base = {
        "task_status": "Open",
        "country": "US",
        "task_type": "Respond to Final Office Action - 4 Month Deadline",
        "sep_status": None,
        "tier": None,
    }
    base.update(overrides)
    return base


def _ep_oa_entry(**overrides):
    base = {
        "task_status": "Open",
        "country": "EP",
        "task_type": "Foreign: EP - Respond to Office Action",
        "sep_status": None,
        "tier": None,
    }
    base.update(overrides)
    return base


def _sep_entry(**overrides):
    base = {
        "task_status": "Open",
        "country": "US",
        "task_type": "Respond to Non-Final Office Action - 3 Month Deadline",
        "sep_status": "5G NR",
        "tier": None,
    }
    base.update(overrides)
    return base


class TestUsNonFinalRule:
    def test_matches_and_generates_tasks(self):
        entry = _us_nonfinal_entry()
        tasks = generate_tasks_for_entry(entry)
        names = [t["name"] for t in tasks]
        assert any("Review Office Action" in n for n in names)
        assert any("FILE RESPONSE" in n for n in names)

    def test_tasks_sorted_by_offset_descending(self):
        entry = _us_nonfinal_entry()
        tasks = generate_tasks_for_entry(entry)
        offsets = [t["offset_days"] for t in tasks]
        assert offsets == sorted(offsets, reverse=True)

    def test_closed_entry_produces_no_tasks(self):
        entry = _us_nonfinal_entry(task_status="Closed")
        tasks = generate_tasks_for_entry(entry)
        # No rule should fire for a closed entry
        assert tasks == []

    def test_wrong_country_produces_no_nonfinal_tasks(self):
        # EP entry should not match us_nonfinal_oa_response
        entry = _us_nonfinal_entry(country="EP")
        tasks = generate_tasks_for_entry(entry)
        nonfinal_task_names = [
            t["name"] for t in tasks if "Review Office Action" in t["name"]
            and "foreign" not in t["name"].lower()
        ]
        # The us_nonfinal rule should NOT fire; the foreign rule may fire
        us_rule_tasks = [t for t in tasks if t.get("help_key") == "review_office_action"
                         and t["offset_days"] == 75]
        assert not us_rule_tasks


class TestUsFinalRule:
    def test_matches_final_oa(self):
        entry = _us_final_entry()
        tasks = generate_tasks_for_entry(entry)
        names = [t["name"] for t in tasks]
        assert any("Final OA" in n or "final" in n.lower() for n in names)
        assert any("FILE RCE" in n for n in names)

    def test_notice_of_appeal_matches(self):
        entry = _us_final_entry(task_type="File Notice of Appeal - 4 Month Deadline")
        tasks = generate_tasks_for_entry(entry)
        assert len(tasks) > 0


class TestSepRule:
    def test_sep_adds_additional_tasks(self):
        sep_entry = _sep_entry()
        plain_entry = _us_nonfinal_entry()
        sep_tasks = generate_tasks_for_entry(sep_entry)
        plain_tasks = generate_tasks_for_entry(plain_entry)
        # SEP entry should have more tasks
        assert len(sep_tasks) > len(plain_tasks)
        sep_names = [t["name"] for t in sep_tasks]
        assert any("SEP" in n or "Avanci" in n or "3GPP" in n for n in sep_names)


class TestDeduplication:
    def test_same_task_from_two_rules_deduped(self):
        """If two rules generate a task with the same name, keep the one with
        the largest offset_days."""
        # An entry that could match both us_nonfinal and sep_avanci rules
        # will have some tasks generated by both; check no exact-name duplicates
        entry = _sep_entry()
        tasks = generate_tasks_for_entry(entry)
        names_lower = [t["name"].lower() for t in tasks]
        # All names should be unique (case-insensitive)
        assert len(names_lower) == len(set(names_lower))

    def test_dedup_keeps_highest_offset(self):
        """Deduplication keeps the task with the highest offset_days."""
        # Inject a scenario by directly calling with an entry that triggers
        # overlapping task names. Here we rely on the fact that sep rule
        # produces "Confirm SEP status..." at offset 80, which is unique,
        # so no conflict — but we verify the merge logic generically.
        entry = _sep_entry()
        tasks = generate_tasks_for_entry(entry)
        name_to_offsets: dict[str, list[int]] = {}
        for t in tasks:
            key = t["name"].lower()
            name_to_offsets.setdefault(key, []).append(t["offset_days"])
        for name, offsets in name_to_offsets.items():
            assert len(offsets) == 1, f"Duplicate task after dedup: {name!r}"


class TestForeignRule:
    def test_ep_oa_matches_foreign_rule(self):
        entry = _ep_oa_entry()
        tasks = generate_tasks_for_entry(entry)
        assert len(tasks) > 0
        names = [t["name"] for t in tasks]
        assert any("foreign associate" in n.lower() or "foreign office action" in n.lower()
                   for n in names)

    def test_us_entry_not_matched_by_foreign_rule(self):
        entry = _us_nonfinal_entry()
        tasks = generate_tasks_for_entry(entry)
        # "Authorize filing; confirm filing by foreign associate" should not appear
        names = [t["name"] for t in tasks]
        assert not any("foreign associate" in n.lower() for n in names)


class TestNoMatchEntry:
    def test_no_matching_rule_produces_empty_list(self):
        entry = {
            "task_status": "Open",
            "country": "US",
            "task_type": "Some Unknown Task Type XYZ",
            "sep_status": None,
            "tier": None,
        }
        tasks = generate_tasks_for_entry(entry)
        assert tasks == []
